# Generated by Django 5.1.1 on 2024-10-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0010_alter_hotel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('offer_duration', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ManyToManyField(related_name='offer', to='hotel.hotel')),
            ],
        ),
    ]
