# Generated by Django 5.1.1 on 2024-10-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
