# Generated by Django 5.1.1 on 2024-10-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_offer', '0002_specialoffer_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='offer_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
