# Generated by Django 5.1.1 on 2024-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_offer', '0003_alter_specialoffer_offer_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='discount',
            field=models.IntegerField(default=None),
        ),
    ]
