# Generated by Django 5.1.1 on 2024-10-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_or_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestoradmin',
            name='admin_request',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='guestoradmin',
            name='is_mastar_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
