# Generated by Django 5.1.1 on 2024-10-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_or_admin', '0002_guestoradmin_admin_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestoradmin',
            old_name='is_mastar_admin',
            new_name='is_master_admin',
        ),
    ]
