# Generated by Django 5.0.6 on 2024-07-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_booking_status'),
        ('guest', '0003_alter_guest_account'),
        ('transaction', '0004_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='guest',
            field=models.ManyToManyField(null=True, to='guest.guest'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='booking',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ManyToManyField(null=True, to='booking.booking'),
        ),
    ]
