# Generated by Django 5.1.1 on 2024-10-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_transaction_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_types',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Booking', 'Booking'), ('Deposit', 'Deposit')], default='Deposit', max_length=20),
        ),
    ]
