# Generated by Django 5.0.6 on 2024-07-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_transaction_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_types',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Deposit', 'Deposit'), ('Withdraw', 'Withdraw')], max_length=20),
        ),
    ]
