# Generated by Django 5.0.6 on 2024-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_alter_transaction_transaction_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_types',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Deposit', 'Deposit'), ('Withdraw', 'Withdraw')], max_length=20),
        ),
    ]
