# Generated by Django 5.0.6 on 2024-07-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_booking_booking_status'),
        ('guest', '0004_alter_guest_user'),
        ('transaction', '0017_alter_transaction_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ManyToManyField(to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='guest',
            field=models.ManyToManyField(to='guest.guest'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Success', 'Success'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_types',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit'), ('Booking', 'Booking')], default='Deposit', max_length=20),
        ),
    ]
