# Generated by Django 5.0.6 on 2024-07-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_booking_booking_status'),
        ('guest', '0004_alter_guest_user'),
        ('transaction', '0018_alter_transaction_booking_alter_transaction_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='guest',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Success', 'Success')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_types',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Booking', 'Booking')], default='Deposit', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.guest'),
        ),
    ]
