# Generated by Django 5.1.1 on 2024-10-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0029_alter_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_types',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Deposit', 'Deposit'), ('Failed', 'Failed'), ('Booking', 'Booking')], default='Deposit', max_length=20),
        ),
    ]
