# Generated by Django 5.1.1 on 2024-11-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0033_transaction_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_types',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Failed', 'Failed'), ('Booking', 'Booking'), ('Deposit', 'Deposit')], default='Deposit', max_length=20),
        ),
    ]
