# Generated by Django 5.1.1 on 2024-10-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Checked-out', 'Checked-out'), ('Checked-in', 'Checked-in'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
