# Generated by Django 5.0.6 on 2024-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Checked-in,', 'Checked-in'), ('Confirmed', 'Confirmed'), ('Checked-out', 'Checked-out')], default='Pending', max_length=20),
        ),
    ]
