# Generated by Django 5.0.6 on 2024-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Checked-in,', 'Checked-in'), ('Checked-out', 'Checked-out'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
