# Generated by Django 5.0.6 on 2024-07-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_booking_booking_status_alter_booking_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Checked-in,', 'Checked-in'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Checked-out', 'Checked-out'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
