# Generated by Django 5.0.6 on 2024-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Checked-out', 'Checked-out'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Checked-in', 'Checked-in'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
