# Generated by Django 5.0.6 on 2024-07-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_alter_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Checked-in', 'Checked-in'), ('Confirmed', 'Confirmed'), ('Checked-out', 'Checked-out')], default='Pending', max_length=20),
        ),
    ]
