# Generated by Django 5.1.1 on 2024-10-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐'), ('3', '⭐⭐⭐')], max_length=20),
        ),
    ]
