# Generated by Django 5.1.1 on 2024-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('3', '⭐⭐⭐'), ('2', '⭐⭐'), ('4', '⭐⭐⭐⭐'), ('1', '⭐'), ('5', '⭐⭐⭐⭐⭐')], max_length=20),
        ),
    ]
