# Generated by Django 5.0.6 on 2024-07-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_remove_review_hotel_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('3', '⭐⭐⭐'), ('1', '⭐'), ('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('2', '⭐⭐')], max_length=20),
        ),
    ]
