# Generated by Django 5.1.1 on 2024-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '⭐'), ('4', '⭐⭐⭐⭐'), ('2', '⭐⭐'), ('5', '⭐⭐⭐⭐⭐'), ('3', '⭐⭐⭐')], max_length=20),
        ),
    ]
