# Generated by Django 5.0.6 on 2024-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('4', '⭐⭐⭐⭐'), ('2', '⭐⭐'), ('5', '⭐⭐⭐⭐⭐'), ('1', '⭐'), ('3', '⭐⭐⭐')], max_length=20),
        ),
    ]
