# Generated by Django 5.1.1 on 2024-10-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('2', '⭐⭐'), ('4', '⭐⭐⭐⭐'), ('1', '⭐'), ('5', '⭐⭐⭐⭐⭐'), ('3', '⭐⭐⭐')], max_length=20),
        ),
    ]
