# Generated by Django 5.0.6 on 2024-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('1', '⭐'), ('5', '⭐⭐⭐⭐⭐'), ('2', '⭐⭐')], max_length=20),
        ),
    ]
