# Generated by Django 5.0.6 on 2024-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0025_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐'), ('5', '⭐⭐⭐⭐⭐')], max_length=20),
        ),
    ]
