# Generated by Django 5.1.1 on 2024-10-26 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_alter_hotel_rating'),
        ('review', '0026_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('5', '⭐⭐⭐⭐⭐'), ('1', '⭐'), ('4', '⭐⭐⭐⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐')], max_length=20),
        ),
    ]
