# Generated by Django 5.1.1 on 2024-10-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0027_review_hotel_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('2', '⭐⭐'), ('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('1', '⭐'), ('5', '⭐⭐⭐⭐⭐')], max_length=20),
        ),
    ]
