# Generated by Django 5.1.1 on 2024-10-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0028_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('3', '⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐'), ('4', '⭐⭐⭐⭐')], max_length=20),
        ),
    ]
