# Generated by Django 5.1.1 on 2024-10-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0030_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '⭐'), ('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐'), ('2', '⭐⭐')], max_length=20),
        ),
    ]
