# Generated by Django 5.1.1 on 2024-11-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0032_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('2', '⭐⭐'), ('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐'), ('1', '⭐')], max_length=20),
        ),
    ]
