# Generated by Django 5.1.1 on 2024-10-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_alter_hotel_rating_hotelscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟'), ('🌟🌟', '🌟🌟'), ('🌟🌟🌟', '🌟🌟🌟'), ('🌟', '🌟')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelscategory',
            name='hotel',
            field=models.ManyToManyField(related_name='category', to='hotel.hotel'),
        ),
    ]
