# Generated by Django 5.1.1 on 2024-10-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_remove_hotel_included_category_alter_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='included_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('🌟', '🌟'), ('🌟🌟🌟', '🌟🌟🌟'), ('🌟🌟', '🌟🌟'), ('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟')], max_length=10),
        ),
    ]
