# Generated by Django 5.1.1 on 2024-10-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_hotel_included_category_alter_hotel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=300)),
                ('size', models.CharField(max_length=400)),
                ('capacity', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=None)),
                ('images', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('location', models.JSONField(default=list)),
                ('amenity', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('🌟🌟🌟', '🌟🌟🌟'), ('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟'), ('🌟🌟', '🌟🌟'), ('🌟', '🌟')], max_length=10),
        ),
    ]
