# Generated by Django 5.1.1 on 2024-10-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestroom',
            name='location',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟'), ('🌟🌟', '🌟🌟'), ('🌟', '🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟'), ('🌟🌟🌟', '🌟🌟🌟')], max_length=10),
        ),
    ]
