# Generated by Django 5.1.1 on 2024-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_rename_amenity_bestroom_amenities_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('🌟🌟🌟', '🌟🌟🌟'), ('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟'), ('🌟🌟', '🌟🌟'), ('🌟', '🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟')], max_length=10),
        ),
    ]
