# Generated by Django 5.1.1 on 2024-10-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_alter_hotel_rating'),
        ('review', '0028_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='feedback', to='review.review'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('🌟', '🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟'), ('🌟🌟🌟', '🌟🌟🌟'), ('🌟🌟', '🌟🌟'), ('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟')], max_length=10),
        ),
    ]
